using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DietSync.Models
{
    // Represents the input model for creating or updating a user profile
    public class UserProfileInputModel
    {
        [Key] // Specifies that UserId is the primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Specifies that the UserId is auto-generated by the database
        public int UserId { get; set; }

        [MaxLength(50)]
        public string Username { get; set; }

        [Required]
        [EmailAddress]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(50)]
        public string LastName { get; set; }

        [Required]
        [MinLength(8, ErrorMessage = "Password must be at least 8 characters long.")]
        public string Password { get; set; }
    }
}