using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DietSync.Models
{
    [Table("userProfile")] // Maps this class to the "userProfile" table in the database
    public class UserProfile
    {
        [Key] // Specifies that UserId is the primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Specifies that the UserId is auto-generated by the database
        public int UserId { get; set; }

        [MaxLength(50)] // Limits the maximum length of Username to 50 characters
        public string Username { get; set; }

        [MaxLength(255)] // Limits the maximum length of Password to 255 characters
        public string Password { get; set; }

        [MaxLength(100)] // Limits the maximum length of Email to 100 characters
        public string Email { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public DateTime? DateofBirth { get; set; }
        public string? Gender { get; set;}
        public int? Weight { get; set; }
        public int? Height { get; set; }
        public string? Membership { get; set; }
        public ICollection<Recipe> Recipes { get; set; }

    }
}